version: '3'

services:
  web:
    build: ./
    networks:
      - default
      - localhost
    env_file:
      - .env
    environment:
      - VIRTUAL_HOST=${DOMAIN}
      - VIRTUAL_PORT=80
      - WP_HOME=http://${DOMAIN}
      - SKIP_CHOWN=1
      - PUID=1000
      - SSMTP_URI=ssmtp://mailcatcher:25
      - SSMTP_DEFAULT_FROM=info@docker.local
      - ENABLE_XDEBUG=1
    volumes:
      - ./:/var/www/html:Z

networks:
  localhost:
    external: true
