version: '3'

services:
  web:
    build: ./
    image: blog:latest
    networks:
    - default
    - proxy
    - dbaas
    env_file:
    - .env
    environment:
    - VIRTUAL_HOST=${DOMAIN}
    - VIRTUAL_PORT=80
    - WP_HOME=http://${DOMAIN}
    - SKIP_CHOWN=1
    - PUID=1000
    volumes:
    - ./:/var/www/html:Z

  # memcached:
  #   image: memcached:1.5-alpine
  #   volumes:
  #     - cache:/var/lib/memcached

# volumes:
#   mysql:
#     driver: local
#   cache:
#     driver: local

networks:
  proxy:
    external: true
  dbaas:
    external: true
